# services are the containers. they are ordered based on their dependencies
services:
  # mariadb container
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
  #wordpress container
  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    container_name: wordpress
    restart: unless-stopped # @todo change to unless-stopped
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
  # nginx container
  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
      args:
        - DOMAIN_NAME=${DOMAIN_NAME}
    container_name: nginx
    restart: unless-stopped
    env_file:
      - .env
    # to access a container from outside the docker network you need to set the port here
    ports:
      - "443:443"
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    #when debugging containrs set restart to on-failure


    # volumes are dierctories shared between the containers and a different machine (in this case local)
volumes:
  mariadb_data:
    name: volmariadb
    driver: local #volume is located on the host machine
    driver_opts:
      type: none
      device: ${HOME}/inception42_volume/mariadb_data
      o: bind
  wordpress_data:
    name: volwp
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/inception42_volume/wordpress_data
      o: bind

# networks define the communication channels between containers, allowing them to connect and interact with each other
networks:
  inception:
    name: inception_network
    external: false
    driver: bridge
