services:
  wordpress:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ADMIN=${MYSQL_ADMIN}
        - MYSQL_ADMIN_PASSWORD=${MYSQL_ADMIN_PASSWORD}
    container_name: mariadb
    restart: on-failure # @todo change to unless-stopped after debugging
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/inception42_volume/mariadb_data
      o: bind

networks:
  inception:
    name: inception_network
    external: false
