services:
  wordpress:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: wordpress
    restart: on-failure
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ${HOME}/inception42_volume/wordpress_data
      o: bind

networks:
  inception:
    name: inception_network
    external: false