CREATE DATABASE IF NOT EXISTS `${MYSQL_DATABASE}` 
    CHARACTER SET utf8mb4 
    COLLATE utf8mb4_unicode_ci;

-- Root user with full access from any host
DROP USER IF EXISTS 'root'@'%';
CREATE USER 'root'@'%' IDENTIFIED BY '${MYSQL_ROOT_PASSWORD}';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;

-- Regular user
DROP USER IF EXISTS '${MYSQL_USER}'@'%';
CREATE USER '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, ALTER, DROP, INDEX ON `${MYSQL_DATABASE}`.* TO '${MYSQL_USER}'@'%';

-- Admin user
DROP USER IF EXISTS '${MYSQL_ADMIN}'@'%';
CREATE USER '${MYSQL_ADMIN}'@'%' IDENTIFIED BY '${MYSQL_ADMIN_PASSWORD}';
GRANT ALL PRIVILEGES ON `${MYSQL_DATABASE}`.* TO '${MYSQL_ADMIN}'@'%';

FLUSH PRIVILEGES;